name: fijkplayer
description: A Video Player Flutter plugin based on ijkplayer, support most popular protocols and codecs
version: 0.11.0
homepage: https://fijkplayer.befovy.com
repository: https://github.com/befovy/fijkplayer
issue_tracker: https://github.com/befovy/fijkplayer/issues

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.befovy.fijkplayer
        pluginClass: FijkPlugin
      ios:
        pluginClass: FijkPlugin
